/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShapeModel } from './shapeModel';


export interface CardModel { 
    name?: string;
    scryfallId?: string;
    cardType?: CardModel.CardTypeEnum;
    cardLayout?: CardModel.CardLayoutEnum;
    set?: string;
    pictureUri?: string;
    manaCost?: string;
    shapes?: Array<ShapeModel>;
    ready?: boolean;
}
export namespace CardModel {
    export const CardTypeEnum = {
        Creature: 'CREATURE',
        Enchantment: 'ENCHANTMENT',
        Land: 'LAND',
        Artifact: 'ARTIFACT',
        Planeswalker: 'PLANESWALKER',
        Instant: 'INSTANT',
        Sorcery: 'SORCERY',
        Battle: 'BATTLE',
        ArtifactCreature: 'ARTIFACT_CREATURE',
        BasicLand: 'BASIC_LAND'
    } as const;
    export type CardTypeEnum = typeof CardTypeEnum[keyof typeof CardTypeEnum];
    export const CardLayoutEnum = {
        Normal: 'NORMAL',
        Transform: 'TRANSFORM'
    } as const;
    export type CardLayoutEnum = typeof CardLayoutEnum[keyof typeof CardLayoutEnum];
}


