/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShapeModel } from './shapeModel';


export interface MaskModel { 
    id?: number;
    name?: string;
    standard?: boolean;
    shapes?: Array<ShapeModel>;
}

