/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SetEntity { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    scryfallId?: string;
    name?: string;
    code?: string;
    url?: string;
    releaseDate?: string;
    type?: SetEntity.TypeEnum;
    cards?: number;
    iconUrl?: string;
    released?: boolean;
}
export namespace SetEntity {
    export const TypeEnum = {
        Core: 'CORE',
        Expansion: 'EXPANSION',
        Masters: 'MASTERS',
        Alchemy: 'ALCHEMY',
        Masterpiece: 'MASTERPIECE',
        Arsenal: 'ARSENAL',
        FromTheVault: 'FROM_THE_VAULT',
        Spellbook: 'SPELLBOOK',
        PremiumDeck: 'PREMIUM_DECK',
        DuelDeck: 'DUEL_DECK',
        DraftInnovation: 'DRAFT_INNOVATION',
        TreasureChest: 'TREASURE_CHEST',
        Commander: 'COMMANDER',
        Planechase: 'PLANECHASE',
        Archenemy: 'ARCHENEMY',
        Vanguard: 'VANGUARD',
        Funny: 'FUNNY',
        Starter: 'STARTER',
        Box: 'BOX',
        Promo: 'PROMO',
        Token: 'TOKEN',
        Memorabilia: 'MEMORABILIA',
        Minigame: 'MINIGAME'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


