/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShapeModel { 
    id?: number;
    type?: ShapeModel.TypeEnum;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
}
export namespace ShapeModel {
    export const TypeEnum = {
        Mana: 'MANA',
        Type: 'TYPE',
        Text: 'TEXT',
        Pt: 'PT',
        Loyalty: 'LOYALTY'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


